version: "3.3"

services:
  bash-go:
    build: bash-go/.
    image: terryhorner/bash-go:latest
    command: ["/bin/bash"]
    working_dir: /local
    volumes:
      - ./:/local

  bash-python:
    build: bash-python/.
    image: terryhorner/bash-python:latest
    command: ["/bin/bash"]
    working_dir: /local
    volumes:
      - ./:/local

  bash-ruby:
    build: bash-ruby/.
    image: terryhorner/bash-ruby:latest
    command: ["/bin/bash"]
    working_dir: /local
    volumes:
      - ./:/local

  gcloud:
    build: gcloud/.
    image: terryhorner/gcloud:latest
    command: ["/bin/bash"]
    working_dir: /local
    volumes:
      - ./:/local

  gcloud-go:
    build: gcloud-go/.
    image: terryhorner/gcloud-go:latest
    command: ["/bin/bash"]
    working_dir: /local
    volumes:
      - ./:/local
